# Use postgres-base user/password credentials
version: '3.1'

services:

  db:
    image: postgres-base
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: admin
      POSTGRES_DB: admin
    ports:
          - 54321:5432